### ISSUE TITLE
Adjust datepicker layout (Conflict with Give)

### ISSUE THREAD

**Issue by pderksen** [Xtendify/Simple-Calendar#108]
Looks a little strange with outside padding and borders.

This is on calendar start date, but also check elsewhere where the datepicker is used.

![image](https://cloud.githubusercontent.com/assets/79667/12525793/fb89fab6-c11b-11e5-9af6-3040520f3235.png)

**Comment by nickyoung87** [comment]
Yours looks much different than mine. Will look into it though to see if I can find out what's going on.

![2016-01-22_1624](https://cloud.githubusercontent.com/assets/2645164/12525820/bf763d38-c124-11e5-94df-08242fde1e4e.png)

**Comment by pderksen** [comment]
@nickyoung87 Conflict with [Give](https://wordpress.org/plugins/give/). Maybe others using same datepicker library. Better CSS specificity perhaps?

**Comment by nickyoung87** [comment]
@pderksen Looks like Give is adding an extra element around the datepicker `<div class="cmb2-element">`.  I will have to look deeper to see if we can prevent this somehow. If not then we can probably add more style rules so that everything is accounted for.

**Comment by pderksen** [comment]
This is low priority until folks complain. Removing the milestone.

**Comment by nickyoung87** [comment]
6/17/16 - still an issue with latest give version (1.4.5)

**Comment by gacharijohn** [comment]
The issue does not seem replicable at the moment: [https://nimb.ws/mgtrNT](url)
