### ISSUE TITLE
Website Crashes if Google Calendars is down or if any previously available GC is unavailable

### ISSUE THREAD

**Issue by wilirius** [Xtendify/Simple-Calendar#189]
Since GC is currently down, the plugin is causing my website to crash. If there are already conditionals in place to prevent such a thing, then I'll look into more possible reasons that are messing it up on this website. If not, then can we get something in place to prevent this?

This has happened previously when one of the GCs that were being linked to was removed before removing it from the website.

**Comment by nickyoung87** [comment]
What exactly is happening on your site? Does it just make the page go blank or is it affecting the whole site?

**Comment by wilirius** [comment]
White screen, stays loading, then 502s.

The calendar is a grouped one, so if 1 or all fail, it fails.

**Comment by nickyoung87** [comment]
Alright thanks for the update. SO it sounds like Google's calendar service was down this morning? Since that is (likely) a rare case and you mentioned something about removing a calendar could you just list for me some steps here to reproduce the error. That way when I get a chance to look into it I can have all the steps here to dive right in.

Thanks!

**Comment by pixelaviator** [comment]
Hi Nick
I'm getting similar problems with the school website they rely on there google calendar feeds for all kinds of things but we cannot get it working after the outrage. It lists the events as just the word "Events" and has no details or links when you hover over the word "Event" I don't get paid for it but have had to waste my entire weekend trying to sort it. I have been through the theme check, widget check, wiped the plugin and re-installed 4 times, installed the legacy version - it whites out the site on activation. I have had lengthy discussions with our isp regarding the tools reporting an error on ` WP Remote GET No (couldn't connect to host)` They are saying it's an issue with the plugin. 
It seems to me that the recent google outrage has either permanently damaged the plugins ability to operate, or google has not fixed whatever it was that caused this in the first place. Either way the result is a website with a google calendar feed that simply doesn't work. I am out of ideas for what to do next. Is there a way of finding out from google if they have repaired the outrage?
Best regards
Steve

**Comment by wilirius** [comment]
@pixelaviator  - I pulled the entire website's backup from the day before, but yes now certain grouped calendars in list view are just now starting to pull new events.

@nickyoung87 I cannot re-test this to verify as the website is live and the calendars it uses I am not really supposed to mess with, but a testing setup like this would be pretty similar:

1. Create any number > 1 calendars with a separate google calendar as the event source. (so 3 WP calendars for 3 google calendars, or however many...fyi it's 20 in our actual case)
2. Create an "All" grouped calendar from those calendars to display as grid view on /calender/all page.
3. Create a grouped calendar pulling 2 events from previous All calendar in list view to display on the front page.
4. Inside google, delete any of the google calendars from step 1.
5. Website should crash now, although it might need cache to expire.

**Comment by nickyoung87** [comment]
@pixelaviator If it is just showing "Event" then that means there is something either wrong with the event titles or the privacy settings are not set to fully public. I would check those on your Google calendar also. Make sure it is public and that free/busy schedule is NOT checked.

@wilirius Thanks for the update.
