### ISSUE TITLE
Script loading issue with weird strings (PHP 5.3 only)

### ISSUE THREAD

**Issue by nickyoung87** [Xtendify/Simple-Calendar#206]
https://wordpress.org/support/topic/bug-loading-no-existing-scripts

https://wordpress.org/support/topic/widget-requests-requests-non-existing-files

**Comment by pderksen** [comment]
Tested in incognito mode (no browser extensions), default theme, just a few other plugins. Confirmed coming from us. Happens locally too.

**Comment by pderksen** [comment]
Only happens in PHP 5.3.

**Comment by pderksen** [comment]
Low priority. Fixed in PHP 5.4.
