### ISSUE TITLE
Navigation arrows show incorrect icons

### ISSUE THREAD

**Issue by nickyoung87** [Xtendify/Simple-Calendar#210]
I have seen this a few times now. Recent one from HS so won't link that here.

What happens is the icons show as little boxes. I looked into the CSS and found that on the navigation::before it is adding `\E809`. After a bit of searching I found this: http://www.utf8icons.com/character/59401/UTF-8-character

That is the exact match of what shows up. However, in the plugin code there is a reference in this file: https://github.com/moonstonemedia/Simple-Calendar/blob/dev/assets/fonts/simple-calendar.svg (look at it in PHPStorm and you will see).

Is it possible that we are trying to overwrite the encoding or something here and for some reason it doesn't always line up correctly?

**Comment by pderksen** [comment]
Possibly has to do with enqueuing scripts and how it works in a multisite environment. Troubleshooting with customer currently. https://github.com/moonstonemedia/Simple-Calendar/issues/208 may in fact fix it.
