### ISSUE TITLE
qTip showing in footer in certain browsers

### ISSUE THREAD

**Issue by nickyoung87** [Xtendify/Simple-Calendar#221]
https://wordpress.org/support/topic/qtip-is-off-the-page-at-the-bottom/
- Could be theme related but he says it works in Firefox even with the current theme.
- He tried removing the Google map for us but no change.

![qtip_footer](https://cloud.githubusercontent.com/assets/2645164/19488029/617f0156-9522-11e6-9efa-b4905bb6859b.png)

**Comment by pderksen** [comment]
Other qTip issues: #188 #185

**Comment by pderksen** [comment]
Tooltip gets cut off at the bottom on Chrome & Firefox for me. Not sure what they mean by showing in footer though.

![image](https://cloud.githubusercontent.com/assets/79667/19486374/03d1b922-9513-11e6-86a0-5ddfd4dfe9a7.png)

**Comment by nickyoung87** [comment]
@pderksen Updated original.

**Comment by JoshBaker** [comment]
This appears to be an issue where a theme applies position: relative to the <body> tag. 
Removing that relative css fixed the issue in chrome for me - at least as a temporary fix.

**Comment by nickyoung87** [comment]
Sweet, thanks for the info @JoshBaker
