### ISSUE TITLE
Reconsider use of Composer and autoloading (especially Google API PHP library).

### ISSUE THREAD

**Issue by pderksen** [Xtendify/Simple-Calendar#223]
http://blog.wppusher.com/a-warning-about-using-composer-with-wordpress/
https://tommcfarlin.com/php-autoloader-wordpress/

Consider some current and some potential conflicts with other plugins, especially those using different versions of the [Google API PHP library](https://github.com/google/google-api-php-client).

Maybe use composer but customize or remove autoloading?

See recent conflicts with other plugins using the same library. See other plugins using the same library.

Currently `vendor/` contents are _not_ being committed to repo on GitHub (but it for wp.org). Probably should be.
## Specific plugin conflicts
- Ultimate Member - Social Login add-on - see #218 
- Bookly - see #219

**Comment by pderksen** [comment]
Code snippet from UMSL developer:

```
<?php
add_filter("um_social_login_autoload_google","um_custom_social_login_autoload_google", 10, 1);
function um_custom_social_login_autoload_google( $autoload ){
  if( defined("SIMPLE_CALENDAR_VERSION") ){
       return false;
  }
  return $autoload;
} 
?>
```

**Comment by rosinghal** [comment]
Removing this since we are using PHP scoper already
