### ISSUE TITLE
RFE to recurring events in Simple Calendar

### ISSUE THREAD

**Issue by chriswooff** [Xtendify/Simple-Calendar#230]
Some of us have setup recurring events whose first instance is some time in the past and we would like to display a calendar of forthcoming events which only shows the next instance of a recurring event.  “Show All” and “Only Show First Occurrence” don't provide what is needed. This is therefore a request for enhancement for an option something like "next" to show the next occurrence of a recurring event to be provided.

**Comment by nickyoung87** [comment]
@chriswooff I believe this is a duplicate of: https://github.com/moonstonemedia/Simple-Calendar/issues/150

Is that correct? If so, I don't mind closing that one and leaving this one for discussion with you and anyone else.

**Comment by chriswooff** [comment]
Nick yes, that’s right. I put it on github at your suggestion. I am very much in your hands here as if this is going to see the light of day then it is obviously you who will code it up. Please do whatever you think best.

 

Kind regards.

 

--

Yours,

Chris

 

Dr Chris Wooff: chriswooff at fastmail.fm

 

 <http://www.oxfam.org.uk/shop/local-shops> oxfam

**Comment by chriswooff** [comment]
Thanks for adding this. Do I need a paid version to take advantage?


--
Yours,
Chris

The true measure of any society can be found in how it treats its most vulnerable members. (Mahatma Gandhi)
