### ISSUE TITLE
Issue when upgrading to PHP7

### ISSUE THREAD

**Issue by nickyoung87** [Xtendify/Simple-Calendar#244]
https://wordpress.org/support/topic/error-with-php7-2/#post-8626446

User gets an error when upgrading to use PHP7. Not sure what exactly is going on as I am running PHP7 on my dev setup and have not run into this. Could possibly be some other server requirement not being met?

The error: Fatal error: in /home/xxxxxx/public_html/wp-content/plugins/google-calendar-events/includes/feeds/grouped-calendars.php on line 56

Here is the line in question: https://github.com/moonstonemedia/Simple-Calendar/blob/dev/includes/feeds/grouped-calendars.php#L56

Looking at the line could it possibly be something to do with autoloading?

**Comment by nickyoung87** [comment]
More issues coming in about PHP7 compatibility. There has to be something else causing this as I run PHP7.0.8 and have no issue running the plugin.

https://wordpress.org/support/topic/compatible-with-php-7-5/

https://wordpress.org/support/topic/calendar-stopped-displaying-events/

May need to move this up in priority if they keep coming in as something is definitely not right then.

**Comment by gacharijohn** [comment]
@rosinghal PHP 7 has reached end of life hence we can close this.
