### ISSUE TITLE
Fatal error: Cannot redeclare google_api_php_client_autoload()

### ISSUE THREAD

**Issue by nickyoung87** [Xtendify/Simple-Calendar#246]
https://wordpress.org/support/topic/fatal-error-cannot-redeclare-google_api_php_client_autoload/

**Comment by nickyoung87** [comment]
@pderksen Didn't we run into this before? Can you check my reply and see if that rings a bell and sounds correct?

**Comment by gacharijohn** [comment]
@rosinghal the free version of the plugin [https://wordpress.org/plugins/birchschedule/](url) seems discontinued.
