### ISSUE TITLE
Fix compatibility with PHP 7.1

### ISSUE THREAD

**Issue by pderksen** [Xtendify/Simple-Calendar#268]
Need to do this soon. List issues & references here.

- [ ] https://github.com/moonstonemedia/Simple-Calendar/issues/262
- [ ] On https://github.com/moonstonemedia/Simple-Calendar/blob/dev/includes/abstracts/admin-page.php#L182 initialize var `$sanitized` as array. See Help Scout 13179.

**Comment by kalich5** [comment]
https://wordpress.org/support/topic/google-api-key-not-saved/#post-9423353

So what? It’s been half a year and updates are nowhere! When will it support PHP 7.1.x ???

**Comment by damonsharp** [comment]
Hi @kalich5. We are working on PHP 7.1.x support and have it slated for our next release, which will be soon.

**Comment by kalich5** [comment]
ok :-)
