### ISSUE TITLE
Multi-day events in grid view - last day may not show

### ISSUE THREAD

**Issue by ricardito62** [Xtendify/Simple-Calendar#301]
There appears to be an issue with multi-day events in grid view.

The event is not listed for the last day, unless the end time is at least as late in the day as the start time (for example, an event starting at 18:00 on day 1, and ending at 14:00 on day 3, is shown only for days 1 and 2).

Altering the end time to be at least as late in the day as the start time works around this, but is misleading.

**Comment by MartinixH** [comment]
this issue still persists

**Comment by MartinixH** [comment]
I made pull request to fix this.
 #381
