### ISSUE TITLE
PHP Fatal Error Class Carbon not found

### ISSUE THREAD

**Issue by onefiftyfour** [Xtendify/Simple-Calendar#302]
I'm getting this error on a page that does not show the calendar.  When I disable the plugin, this goes error does not occur.  The page in question is from the civicrm plugin while trying to process a payment. 

PHP Fatal error:  Class 'Carbon\\Carbon' not found in /xxxx/xxx/xxxxxx.org/public_html/wp-content/plugins/google-calendar-events/includes/functions/shared.php on line 230

Is there a way of not loading the plugin for a specific page?

**Comment by onefiftyfour** [comment]
I guess this is a duplicate of issue 247

**Comment by Archie22is** [comment]
It doesn't appear to be the same error - I am also experiencing the same error as well after upgrading to PHP 7.0 (it doesn't work on PHP 7.2).

**Comment by Archie22is** [comment]
Okay, the problem seems to have been resolved after upgrading to WordPress 5.1.1

**Comment by rosinghal** [comment]
Closing this since @Archie22is confirmed it is fixed.
