### ISSUE TITLE
Fatal error when updating user pwd

### ISSUE THREAD

**Issue by mdorchain** [Xtendify/Simple-Calendar#310]
Hi, 

when updating user passwords, I get a fatal error coming from simple-calendar.

PHP Fatal error:  Call to undefined method Google_Http_REST::createRequestUri() in /wp-content/plugins/google-calendar-events/vendor/google/apiclient/src/Google/Service/Resource.php on line 192

Looks like the class isn't loaded.I'm still wondering why the plugin does anything on the user edit screen.
My only way around it was to disable the plugin on that page.

**Comment by rosinghal** [comment]
@gacharijohn can you replicate this?

**Comment by rosinghal** [comment]
Akhilesh wasn't able to replicate this. Closing.
