### ISSUE TITLE
Wrong display of week number in German language

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [Xtendify/Simple-Calendar#326]
The date-date-format-field of the heading has the setting "l, d. F Y (KW W)". "KW" is the abbreviation for "KalenderWoche" (German for "Calendar Week"). The problem is, that the second letter of the abbreviation is replaced with the week number like the second "W". This leads to wrong format in which the week number appears two times like "Mittwoch, 25. September 2019 (K39 39)" instead of "Mittwoch, 25. September 2019 (KW 39)".

**Comment by rosinghal** [comment]
@gacharijohn I think this be bypassed by adding a slash `\`. Closing this.
