### ISSUE TITLE
Conflict with WP Mail SMTP Plugin

### ISSUE THREAD

**Issue by kevinvess** [Xtendify/Simple-Calendar#328]
When using this plugin along with the [WP Mail SMTP by WPForms](https://wordpress.org/plugins/wp-mail-smtp/) plugin, I get the following Fatal Error when attempting to test sending emails using Gmail API:

```
Warning: json_decode() expects parameter 1 to be string, array given in /www/wp-content/plugins/google-calendar-events/vendor/google/apiclient/src/Google/Auth/OAuth2.php on line 184

Fatal error: Uncaught Google_Auth_Exception: Could not json decode the token in /www/wp-content/plugins/google-calendar-events/vendor/google/apiclient/src/Google/Auth/OAuth2.php:186
Stack trace:
#0 /www/wp-content/plugins/google-calendar-events/vendor/google/apiclient/src/Google/Client.php(218): Google_Auth_OAuth2->setAccessToken(NULL)
#1 /www/wp-content/plugins/wp-mail-smtp/src/Providers/Gmail/Auth.php(120): Google_Client->setAccessToken(Array)
#2 /www/wp-content/plugins/wp-mail-smtp/src/Providers/Gmail/Auth.php(37): WPMailSMTP\Providers\Gmail\Auth->get_client()
#3 /www/wp-content/plugins/wp-mail-smtp/src/Providers/Gmail/Mailer.php(79): WPMailSMTP\Providers\Gmail\Auth->__construct()
#4 /www/wp-content/plugins/wp-mail-smtp/src/MailCatcher.php(122): WPMailSMTP\Providers\Gmail\Mailer->send()
#5 /www/wp-includes/pluggable.php(488): WPMailSMTP\MailCatcher->send()
#6 /www/wp-content/plugins/wp-mail-smtp/src/Admin/Pages/TestTab.php(172): wp_mail(Array, 'WP Mail SMTP: H...', '\t\t
```

When I disable the Simple Calendar plugin, the WP Mail plugin works.

@awesomemotive
https://github.com/awesomemotive/WP-Mail-SMTP

**Comment by kevinvess** [comment]
Seems I'm not the only one with this issue:
https://wordpress.org/support/topic/500-error-on-email-test-using-gmail-as-a-mailer/

**Comment by ollieknights** [comment]
Keinvess, did you find a resolve to this? Seems like you cannot have a gmail account as a mailer and simple calendar. Its a shame as I love this plug-in but I cant use it because changing our mail provider is not an option. Is this something that's going to be looked at for a workaround?

**Comment by kevinvess** [comment]
@ollieknights I haven't tested this yet, but the _WP Mail SMTP_ plugin author said they're working on fixing this issue for a future release of their plugin:

https://wordpress.org/support/topic/conflict-with-simple-calendar-plugin/

**Comment by mickwall001** [comment]
I have submitted a pull request #342 that should also fix this (and any other dependency clashes)

**Comment by rosinghal** [comment]
Closing this issue since https://github.com/Xtendify/Simple-Calendar/pull/342 was merged.
