### ISSUE TITLE
Use lighter alternative to moment.js

### ISSUE THREAD

**Issue by mjenczmyk** [Xtendify/Simple-Calendar#339]
Hi,

`moment.js` is a heavy package and it affects performance and speed of the websites using this plugin. There are lighter alternatives having similar functionalities (not all of `moment.js` functionalities, but still sufficent subset) - [`date-fns`](https://date-fns.org/) for instance, which weights 18 KiB (compared to 70.4 KiB of `moment.js`). Would you accept a pull request replacing `moment.js` usage?

**Comment by estlacksensory** [comment]
Please look into this. Moment.js is throwing some "Best Practices" errors when testing in Lighthouse (known security vulnerability for library). Moment.js@2.18.1

**Comment by rosinghal** [comment]
https://day.js.org/ is also a good alternative

**Comment by bmos** [comment]
The [version](https://security.snyk.io/package/npm/moment/2.18.1) of Moment.js used also has known vulnerabilities. Google's PageSpeed Insights tool also warns about this.
I think they also rate sites with vulnerabilities lower, but not 100% sure of that.

**Comment by rosinghal** [comment]
@bmos sorry about the bad experience earlier, we will address this in our next release.

**Comment by rosinghal** [comment]
@bmos @mjenczmyk @estlacksensory 
I have created PR #397 to replace Moment with Dayjs. Would you guys be interested in testing if it works correctly?

**Comment by bmos** [comment]
I tried downloading the repo zip and installing into a test site but then the homepage wouldn't load anymore so I uninstalled it.

**Comment by rosinghal** [comment]
@bmos please try using this zip.
[simple-calendar-3.1.38.zip](https://github.com/Xtendify/Simple-Calendar/files/10985427/simple-calendar-3.1.38.zip)

**Comment by bmos** [comment]
Thanks! It installs and activates now and seems to be working.
No more error in PageSpeed Insights and all the features I use seems to be good.
Can't really speak to the speed.
