### ISSUE TITLE
Plugin not compatible with WP 5.8

### ISSUE THREAD

**Issue by ShermanNauss** [Xtendify/Simple-Calendar#348]
Plugin needs update as currently it mess the WP 5.8 leading to an unreachable or messy design website.

**Comment by nickyoung87** [comment]
Did you run into an issue running it on 5.8? If so could you provide some more details?

Thanks!

**Comment by ShermanNauss** [comment]
> Did you run into an issue running it on 5.8? If so could you provide some more details?
> 
> Thanks!

Yes, it first looked working fine, then I noticed that the website looks messy where all items in the home page are not functioning properly (example: the slider is not rotating pics but rather listing all slider pictures under each other). In many times when you visit the website, it shows an error message and that the website is not reachable. Once I deactivated the plugin, everything went back to normal

**Comment by rosinghal** [comment]
@estlacksensory please create a separate issue foe that, I agree we should replace moment.js with either dayjs or date-fns.

Closing this issue since we are already compatible with latest WP.
