### ISSUE TITLE
PHP 8.2 FATAL ERROR

### ISSUE THREAD

**Issue by kalich5** [Xtendify/Simple-Calendar#377]
[Thu Feb 23 19:17:14.429588 2023] [proxy_fcgi:error] [pid 20331:tid 140161436743424] [remote 194.230.148.86:56425] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: SimpleCalendar\\plugin_deps\\Carbon\\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in /home/vu008964/www/wp-content/plugins/google-calendar-events/third-party/nesbot/carbon/src/Carbon/Traits/Creator.php on line 81 and defined in /home/vu008964/www/wp-content/plugins/google-calendar-events/third-party/nesbot/carbon/src/Carbon/Traits/Creator.php:674\nStack trace:\n#0 /home/vu008964/www/wp-content/plugins/google-calendar-events/third-party/nesbot/carbon/src/Carbon/Traits/Creator.php(81): SimpleCalendar\\plugin_deps\\Carbon\\Carbon::setLastErrors()\n#1 /home/vu008964/www/wp-content/plugins/google-calendar-events/third-party/nesbot/carbon/src/Carbon/Traits/Creator.php(212): SimpleCalendar\\plugin_deps\\Carbon\\Carbon->__construct()\n#2 /home/vu008964/www/wp-content/plugins/google-calendar-events/includes/functions/shared.php(241): SimpleCalendar\\plugin_deps\\Carbon\\Carbon::now()\n#3 /home/vu008964/www/wp-content/plugins/...', referer: https://pracata.cz/o-nas/

**Comment by kalich5** [comment]
I see there's already a new version here on GitHub... why isn't it on wordpress.org????

**Comment by rosinghal** [comment]
@kalich5 we were testing with some users before releasing it for all. We just released that on w.org. Thanks for being on top of it. 😍
