### ISSUE TITLE
Fatal Error When Updating a Calendar

### ISSUE THREAD

**Issue by gacharijohn** [Xtendify/Simple-Calendar#380]
There seems to be a Fatal error being generated upon trying to carry updates to a calendar and saving them. The error generated is:

` Fatal error: Uncaught SimpleCalendar\plugin_deps\Google_Service_Exception: { "error": { "errors": [ { "domain": "global", "reason": "notFound", "message": "Not Found" } ], "code": 404, "message": "Not Found" } } in /public/wp-content/plugins/google-calendar-events/third-party/google/apiclient/src/Google/Http/REST.php on line 97`

Screencast: https://app.claap.io/test-35/calendar-c-2mwFVAztrK-_Fdu9PoEiIF3

PHP version 8.1
Wp Version 6.1.1
Plugin version 3.1.37.2

**Comment by rosinghal** [comment]
@gacharijohn please include the version of the plugin, PHP and WP.

**Comment by Perkeo56** [comment]
I've also run into this issue on two instances. Any solution or fix would be appreciated :)

WP: 6.1.1 (both)
PHP: 8.0.27 & 8.0.3
Plugin Version: 3.1.37.2

**Comment by rosinghal** [comment]
@gacharijohn @Perkeo56  can you please verify if https://github.com/Xtendify/Simple-Calendar/releases/download/3.1.38-beta1/simple-calendar-3.1.38-beta1.zip works for you?

**Comment by jacksonp2008** [comment]
Works for me in all use cases in my test environment.  When can I put into production?

**Comment by gacharijohn** [comment]
Seems resolved on my end @rosinghal

**Comment by rosinghal** [comment]
Updated in https://wordpress.org/plugins/google-calendar-events/.

**Comment by jacksonp2008** [comment]
I see it auto-updated on my production site and it fixed the error,
thanks.

However, it seems to have broken some other things. (sorry)

There are no longer tabs for "Events", "Appearance" etc..  they are now
links as shown below.

Also , when in list mode I used to be able to set the # of events to show
on the page.  This appears to be gone as well.

[image: Screen Shot 2023-03-13 at 8.38.25 AM.png]

When I look at the page itself, there is some kind of strange artifact
showing up before the first event.


[image: Screen Shot 2023-03-13 at 8.41.35 AM.png]
Regards,

-Steve

(415)  <https://www.google.com/voice/#phones>827-3525

**Comment by rosinghal** [comment]
@jacksonp2008 seems like your images are not showing here properly, maybe because you sent them via email. Can you please send it directly via Github's UI?

**Comment by jacksonp2008** [comment]
updated above

**Comment by rosinghal** [comment]
@jacksonp2008 I am not able to replicate the behaviour, can you see if https://github.com/Xtendify/Simple-Calendar/releases/download/3.1.38.1/simple-calendar-3.1.38.1.zip fixes it?

**Comment by jacksonp2008** [comment]
Thanks tried this one and it still looks the same here:  (no tabs)

![Screen Shot 2023-03-15 at 10 01 50 AM](https://user-images.githubusercontent.com/1813327/225385497-9964d130-e6f0-4014-bdc4-4118639673e0.png)
