### ISSUE TITLE
 Simple Calendar Widget Display Issue

### ISSUE THREAD

**Issue by gacharijohn** [Xtendify/Simple-Calendar#383]
Upon adding the simple calendar Widget and selecting a calendar within the widget, the calendar is not rendered on the front-end.

Screencast: https://app.claap.io/test-36/cal-c-R4HadjaMgK-8OhoKc-QC3kM 

**Test Env**:
WordPress 6.1.1
Theme: Astra
PHP: 8.1.1
Simple Calendar Version 3.1.37.2 

Issue raised here as well: https://wordpress.org/support/topic/problem-to-add-a-calendar-to-the-sidebar/

**Comment by rosinghal** [comment]
@gacharijohn issue does not seem to have been written entirely.

**Comment by gacharijohn** [comment]
@rosinghal it was a formatting issue. I have updated the query.

**Comment by trashar** [comment]
Hi @gacharijohn 

this is not exactly the problem i tryed to explain in the wordpress board.
In the widget configuration i cant select any calendar. The dropdown has any entries, in your video the calendar "cak" is available.

if the calendar is not rendered in the front end i cannot confirm actually.

My wp version: WordPress 6.1.1 and Simple Calendar Version 3.1.38 

3 screenshots to show it better.

Regards Björn

![2023-03-15 10_17_24-Widgets ‹ Freiwillige Feuerwehr Rhode — WordPress -  InPrivate  – Microsoft​ Edg](https://user-images.githubusercontent.com/6734832/225263511-ffe1fbf7-1239-4fe3-b5f3-6e845bed501e.png)
![2023-03-15 10_17_40-Calendars ‹ Freiwillige Feuerwehr Rhode — WordPress -  InPrivate  – Microsoft​ E](https://user-images.githubusercontent.com/6734832/225263514-9483f673-908d-44da-95b0-f3c4259fb73e.png)
![2023-03-15 10_18_01-Dienstplan (Widget) _ Freiwillige Feuerwehr Rhode und 1 weitere Seite -  InPriva](https://user-images.githubusercontent.com/6734832/225263516-1553789c-07dc-4a41-9395-cdfd6cb3f37a.png)

**Comment by gacharijohn** [comment]
@trashar I have added this in #403

**Comment by gacharijohn** [comment]
Yes. Closing this.
