### ISSUE TITLE
Multi Day events not Properly Displaying

### ISSUE THREAD

**Issue by gacharijohn** [Xtendify/Simple-Calendar#384]
If there is a calendar event set for three days, for example beginning March 22nd 2023 at 4pm and ending March 24 2023 at  5pm, the calendar does not display the event on all days.

Screenshot: https://nimb.ws/MNy6Jk

Issue replicated on;

PHP version 8.1
Wp Version 6.1.1
Plugin version 3.1.37.2

**Comment by rosinghal** [comment]
@gacharijohn seems like a duplicate of https://github.com/Xtendify/Simple-Calendar/issues/384, close if you agree.

**Comment by gacharijohn** [comment]
@rosinghal this is actually #384. I suppose you meant #360 but I think this is different though the issue does not have enough info.

**Comment by rosinghal** [comment]
Sorry, I meant https://github.com/Xtendify/Simple-Calendar/issues/301 @gacharijohn

**Comment by gacharijohn** [comment]
@rosinghal Yes it is
