### ISSUE TITLE
Simple Calendar Widget Calendar Selection Issue

### ISSUE THREAD

**Issue by gacharijohn** [Xtendify/Simple-Calendar#403]
**Issue**: Calendar selection is not possible within the Simple Calendar Widget when using the default Block Editor.

**Replication Steps**
-Navigate to the Appearance > Widgets section
-Add the Simple Calendar Widget block to the sidebar [https://nimb.ws/tAG83K](url)
-Try selecting a calendar from the widget [https://nimb.ws/YkDBmU](url)

**Output**:
-It is not possible to select a calendar

**Expected Output**:
-It should be possible to select the calendar

**Comment by rosinghal** [comment]
@gacharijohn which WP version is this from?

**Comment by gacharijohn** [comment]
@rosinghal version: 6.1.1
