### ISSUE TITLE
Event Bubbles Not Working on Simple Calendar widget

### ISSUE THREAD

**Issue by gacharijohn** [Xtendify/Simple-Calendar#410]
The  Event bubbles on the Simple Calendar Widget do not seem to work.
This issue is replicable in the version Version 3.1.39 release.
It can also be viewed within our demo here: [https://demo.simplecalendar.io/grid-view/widget-mobile/](url)

**Comment by rosinghal** [comment]
Duplicate of https://github.com/Xtendify/Simple-Calendar/issues/407
