### ISSUE TITLE
Date format issue in Narrow Widths on "List" Calendar Types

### ISSUE THREAD

**Issue by gacharijohn** [Xtendify/Simple-Calendar#452]
There seems to be a date formatting issue in List type calendars once the calendar Shortcode is added to a page on a section with a narrow column.

**Replication Steps**:
- Create a new page
- Add a "Custom HTML" block to the page
- Within the block, add the calendar Shortcode within a div tag set to a specific width. Below is an example:

`<div style="width:300px;">[calendar id="50"]</div>`
-Save your changes

**Output**
-The date format rendered within the navigation section on the page is not the date format specified within the calendar itself.
Screenshot: https://nimb.ws/7eJz2V
Expected date format output: https://nimb.ws/ViA5Ig

Topic: https://wordpress.org/support/topic/date-format-for-list-view/

**Comment by rosinghal** [comment]
@gacharijohn markdown for links are wrong, all the links are pointing to https://github.com/Xtendify/Simple-Calendar/issues/url

**Comment by gacharijohn** [comment]
@rosinghal it's now rectified
