### ISSUE TITLE
Integrate Compatibility with Unyson

### ISSUE THREAD

**Issue by gacharijohn** [Xtendify/Simple-Calendar#477]
Issue: If a calendar Shortcode is added to a page and the Unyson plugin is later on activated, the calendar is not rendered within the page.

**Replication Steps**
- Create a new page
- Add a Shortcode block to the page
- Within the block, add a calendar Shortcode 
- Install and activate the Unyson plugin

**Output**

- The Calendar is not rendered upon previewing the page. Instead a text "Calendar Placeholder" is what s rendered.

Screenshot: https://nimb.ws/IEuWNP

**Comment by Akhill2020** [comment]
Make the plugin compatible with Unyson in the latest release of the plugin.
