### ISSUE TITLE
is_print_calendar error if _display_print_calendar never set

### ISSUE THREAD

**Issue by dcavanagh** [Xtendify/Simple-Calendar#571]
index error

https://github.com/Xtendify/Simple-Calendar/blob/cda0965d3cc85dcfc2c8cdc7287cf9d8115440fe/includes/calendars/views/default-calendar-grid.php#L272

Work around - Set _display_print_calendar to yes and save calendar. Set _display_print_calendar to no and save post

**Comment by Akhill2020** [comment]
Fix this in Release 3.4.3.
