### ISSUE TITLE
Custom color settings styles are added as inline style to span element without a class

### ISSUE THREAD

**Issue by nickyoung87** [Xtendify/Simple-Calendar#96]

**Comment by nickyoung87** [comment]
I don't think this is worth the hassle at the moment. I did some testing and it is possible for us to do. We can tap into `wp_head` and add a custom `<style>` block there above the theme and plugin CSS files so that it will cascade correctly. The problem though right now is there are little traces of this all over to make things work nicely. For instance, when you set the color to a dark color it makes the text white and vice versa. 

Right now users can use `!important` if they _really_ need to use CSS for some reason to change the heading colors, but we should just direct them to use the color settings as they can use that to set it to any color anyway.

**Comment by pderksen** [comment]
It sounds like you have the right idea/solution for it. Inject inline CSS using classes so it's not set straight to the inline styles, thus can be overridden with a custom CSS file/block.

Look at what other well known plugins do too.

Do for 3.0.17 if straight-forward. Push to 3.0.18 if lengthy.

**Comment by nickyoung87** [comment]
@pderksen So I was curious if there was any sort of "best practice" for this kind of thing and interestingly I found this: https://codex.wordpress.org/Function_Reference/wp_add_inline_style

It looks like exactly what we are trying to do. I am going to give that a shot first and see if we can work it in. If you disagree please let me know.

**Comment by nickyoung87** [comment]
So I set this up now to just add the inline styles to the array already being used to load the styles. This let's us hook the `wp_add_inline_style()` at the correct time. However, now there is a bit of timing issue with the Calendar object itself. We need to grab the color from the object but it is not loaded yet when we are calling this. If we can figure out that little timing issue and make sure the object is already loaded AND be able to still add the inline style correctly then we should be golden.

**Comment by nickyoung87** [comment]
This goes a bit deeper than just the colors it seems. There is a div with a `min-height` set to it inline. A user asked about how to change the size so the best I could do at the time was offer this: https://gist.github.com/nickyoung87/2368b85a3872b6cc1eb71c85dfb3166b

That element may be able to be remedied with a class name or something though, but it just opens my eyes up a little bit more that we need to check for this kind of occurrence in all areas of the plugin.

**Comment by gacharijohn** [comment]
Closing this as it is not an in demand request
